### ISSUE TITLE
[BUG] Documentation: `nix_conf`

### ISSUE THREAD

**Issue by peterbecich** [nix-community/cache-nix-action#131]
## Describe the bug

In the documentation

```
- uses: nixbuild/nix-quick-install-action@v30
  nix_conf: |
    keep-env-derivations = true
    keep-outputs = true
```
is the `nix_conf` a valid option? My GitHub Action errors with that: https://github.com/peterbecich/purescript-bridge/actions/runs/14819255629/workflow

I see `nix_conf` mentioned here https://github.com/nixbuild/nix-quick-install-action

## To Reproduce

Any GitHub Action with that exact `yaml`.

Thanks

**Comment by deemp** [comment]
@peterbecich you should provide inputs to actions using the [`with`](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith) attribute:

```yaml
- uses: nixbuild/nix-quick-install-action@v30
  with:
    nix_conf: |
      keep-env-derivations = true
      keep-outputs = true
```
