### ISSUE TITLE
[BUG] Cache miss even though cache key is present

### ISSUE THREAD

**Issue by peterwaller-arm** [nix-community/cache-nix-action#147]
## Describe the bug

I'm seeing cache misses in action runs even though the cache shows an entry present.

One obvious symptom is that we're ending up with multiple keys for the same thing in the 'caches' view on the actions tab, even though one cache entry was created long after the original cache entry was present.

![Image](https://github.com/user-attachments/assets/fb5bf51f-19c1-4f41-b7d6-8335fdba8357)

I'm seeing, e.g:

![Image](https://github.com/user-attachments/assets/6ab55e06-6801-483d-ba00-3f234abfcb5f)

```
Searching for a cache with the key "nix-Linux-X64-816cb094e718e0c094e614509555f8fec465d16663920bfd305008b23029cdfd".
Could not find a cache with the given "primary-key" and "paths".
Searching for a cache using the "restore-prefixes-first-match":
["nix-Linux-X64"]
Could not find a cache.
```

## To Reproduce

My configuration is:
```yaml
      - uses: nix-community/cache-nix-action@main
        with:
          primary-key: nix-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ runner.arch }}
```

I'm frequently getting cache misses. Not always though.

## Expected behavior

Cache hits when the cache key is obviously present, or an explanation of why it is being ignored.

## Additional context

I don't know much about the details of how this is supposed to work, if the behaviour I'm seeing would be expected or not.

There seem to be other reports of this kind of behaviour, e.g. on https://github.com/actions/cache/issues/1606.

Originally discussed at https://github.com/elfshaker/elfshaker/pull/132.
