### ISSUE TITLE
[BUG] Nothing is cached when CI is red

### ISSUE THREAD

**Issue by hissssst** [nix-community/cache-nix-action#37]
## Describe the bug

```yaml
    - name: Restore and cache Nix store
      uses: nix-community/cache-nix-action@v5
      continue-on-error: true
      with:
        # restore and save a cache using this key
        primary-key: nix-${{ runner.os }}-${{  hashFiles('flake.nix', 'flake.lock', 'nix/ci-shell.nix') }}
        # if there's no cache hit, restore a cache by this prefix
        restore-prefixes-first-match: nix-${{ runner.os }}-
        # collect garbage until Nix store size (in bytes) is at most this number
        # before trying to save a new cache
        gc-max-store-size-linux: 1073741824
        # do purge caches
        purge: true
        # purge all versions of the cache
        purge-prefixes: cache-${{ runner.os }}-
        # created more than this number of seconds ago relative to the start of the `Post Restore` phase
        purge-created: 0
        # except the version with the `primary-key`, if it exists
        purge-primary-key: never
```

Continue on error is set, but post actions is ignored when some consecutive action fails, what essentially makes this action useless, since nobody reruns green CI.

I can't provide a real work-example, since the project is closed-source
