### ISSUE TITLE
[BUG] restore-prefixes-first-match still triggers when primary key matches

### ISSUE THREAD

**Issue by kristoff3r** [nix-community/cache-nix-action#43]
## Describe the bug

I use the action like this:
```yaml
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('./flake.nix', './flake.lock') }}-${{ hashFiles('./src/**/*.nix')}}
          restore-prefixes-first-match: nix-${{ runner.os }}-${{ hashFiles('./flake.nix', './flake.lock') }}
          gc-max-store-size-linux: 1073741824
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never
```
The idea is that it would try to find an exact cache, and then fallback to one with the same flake/lock otherwise. But even when it hits a primary key it still tries to restore from prefixes, resulting in the same cache being restored twice:
```
Run nix-community/cache-nix-action@v5
  
Searching for a cache with the key "nix-Linux-5d8aa1663a7b1fa3908160613db3082990513dc6f220490f58e278604f59ab79-880ef0004b92be6813dd054d992a06382d688d9bd2cf3cc7c8201dc7ab670084".
Lookup only - skipping download
Found a cache with the given "primary-key".
Copying "/nix/var/nix/db/db.sqlite" to "/home/runner/work/_temp/bb6847dc-b1e6-43e8-a639-9a6fa9e284df/old.sqlite".
Restoring a cache with the key "nix-Linux-5d8aa1663a7b1fa3908160613db3082990513dc6f220490f58e278604f59ab79-880ef0004b92be6813dd054d992a06382d688d9bd2cf3cc7c8201dc7ab670084".
Logs produced while restoring a cache.
Finished restoring the cache.
Copying "/nix/var/nix/db/db.sqlite" to "/home/runner/work/_temp/bb6847dc-b1e6-43e8-a639-9a6fa9e284df/new.sqlite".
Merging store databases "/home/runner/work/_temp/bb6847dc-b1e6-43e8-a639-9a6fa9e284df/old.sqlite" and "/home/runner/work/_temp/bb6847dc-b1e6-43e8-a639-9a6fa9e284df/new.sqlite"
into "/nix/var/nix/db/db.sqlite".
/usr/bin/bash -c sqlite3 /nix/var/nix/db/db.sqlite < /home/runner/work/_temp/bb6847dc-b1e6-43e8-a639-9a6fa9e284df/merge.sql
Checking the store database.
/usr/bin/bash -c sqlite3 "/nix/var/nix/db/db.sqlite" 'PRAGMA integrity_check;'
ok
Searching for a cache using the "restore-prefixes-first-match":
["nix-Linux-5d8aa1663a7b1fa3908160613db3082990513dc6f220490f58e278604f59ab79"]
Lookup only - skipping download
Found a cache using the "restore-prefixes-first-match".
Copying "/nix/var/nix/db/db.sqlite" to "/home/runner/work/_temp/7b5b1f43-9e24-416b-af4f-2b86d9465f47/old.sqlite".
Restoring a cache with the key "nix-Linux-5d8aa1663a7b1fa3908160613db3082990513dc6f220490f58e278604f59ab79-880ef0004b92be6813dd054d992a06382d688d9bd2cf3cc7c8201dc7ab670084".
Logs produced while restoring a cache.
Finished restoring the cache.
Copying "/nix/var/nix/db/db.sqlite" to "/home/runner/work/_temp/7b5b1f43-9e24-416b-af4f-2b86d9465f47/new.sqlite".
Merging store databases "/home/runner/work/_temp/7b5b1f43-9e24-416b-af4f-2b86d9465f47/old.sqlite" and "/home/runner/work/_temp/7b5b1f43-9e24-416b-af4f-2b86d9465f47/new.sqlite"
into "/nix/var/nix/db/db.sqlite".
/usr/bin/bash -c sqlite3 /nix/var/nix/db/db.sqlite < /home/runner/work/_temp/7b5b1f43-9e24-416b-af4f-2b86d9465f47/merge.sql
Checking the store database.
/usr/bin/bash -c sqlite3 "/nix/var/nix/db/db.sqlite" 'PRAGMA integrity_check;'
ok
```

## Expected behavior

The workflow should skip `restore-prefixes-first-match` when a cache has already been found, as described in the documentation.
