### ISSUE TITLE
[BUG] Action fails to save cache due to some permission issues

### ISSUE THREAD

**Issue by pshirshov** [nix-community/cache-nix-action#48]
Job:

```yaml
on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  actions: write

jobs:
  build-unix:
    strategy:
      fail-fast: false
      matrix:
        # 1) don't forget about os entry in prepare-release
        # 2) see : https://github.com/actions/runner-images
        include:
          - target: linux-amd64
            os: ubuntu-latest
            runs-on: [ ]
          - target: macos-aarch64-14
            runs-on: [ ]
            os: macos-14 # yes, this is aarch64
            java-version: '23'
          - target: macos-amd64-13
            os: macos-13 # this is amd64
            runs-on: [ ]
            java-version: '23'
    name: ${{ matrix.target }}
    runs-on:
      - ${{ matrix.os }}
      - ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Restore and cache Nix store
        uses: nix-community/cache-nix-action@v5
        with:
          # restore and save a cache using this key
          primary-key: nix-${{ matrix.target }}-${{ hashFiles('**/*.nix') }}
          # if there's no cache hit, restore a cache by this prefix
          restore-prefixes-first-match: nix-${{ matrix.target }}-
          gc-max-store-size-linux: 1073741824
          # do purge caches
          purge: true
          # purge all versions of the cache
          purge-prefixes: cache-${{ matrix.target }}-
          # created more than this number of seconds ago relative to the start of the `Post Restore` phase
          purge-created: 0
          # except the version with the `primary-key`, if it exists
          purge-primary-key: never
```

Failure:

```
Post job cleanup.
Trying to save a new cache with the key "nix-linux-amd64-c50eda80aadc1450fbd38df6b73e938339ee77e95b4667ae1bcefe7b9e437968".
Purging cache(s) created before 2024-10-24T14:38:05.105Z, scoped to "refs/heads/main", and with the key "nix-linux-amd64-c50eda80aadc1450fbd38df6b73e938339ee77e95b4667ae1bcefe7b9e437968".
Found no cache(s).
Finished purging cache(s).
Searching for a cache with the key "nix-linux-amd64-c50eda80aadc1450fbd38df6b73e938339ee77e95b4667ae1bcefe7b9e437968".
Found no cache with this key.
Removing useless files.
/usr/bin/bash -c sudo rm -rf /nix/.[!.]* /nix/..?*
/usr/bin/bash -c 
    STORE_SIZE="$(nix path-info --json --all | jq 'map(.narSize) | add')"    
    printf "Current store size in bytes: $STORE_SIZE\n"
    
Current store size in bytes: 3284910896
Collecting garbage.
/usr/bin/bash -c 
            MAX_STORE_SIZE=1073741824
            
            if (( STORE_SIZE > MAX_STORE_SIZE )); then
                (( R1 = STORE_SIZE - MAX_STORE_SIZE ))
                (( R2 = R1 > 0 ? R1 : 0 ))
                printf "Max bytes to free: $R2\n"
                nix store gc --max "$R2"
            fi
            
Finished collecting garbage.
/usr/bin/bash -c 
    STORE_SIZE="$(nix path-info --json --all | jq 'map(.narSize) | add')"    
    printf "Current store size in bytes: $STORE_SIZE\n"
    
Current store size in bytes: 3284910896
Saving a new cache with the key "nix-linux-amd64-c50eda80aadc1450fbd38df6b73e938339ee77e95b4667ae1bcefe7b9e437968".
/usr/bin/tar --posix -cf cache.tzst --exclude cache.tzst -P -C /home/runner/work/baboon/baboon --files-from manifest.txt --use-compress-program zstdmt
/usr/bin/tar: ../../../../../nix/var/nix/daemon-socket/socket: socket ignored
/usr/bin/tar: ../../../../../nix/var/nix/userpool/30001: Cannot open: Permission denied
/usr/bin/tar: ../../../../../nix/var/nix/gc.lock: Cannot open: Permission denied
/usr/bin/tar: ../../../../../nix/var/nix/db/big-lock: Cannot open: Permission denied
/usr/bin/tar: ../../../../../nix/var/nix/db/reserved: Cannot open: Permission denied
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Failed to save: "/usr/bin/tar" failed with error: The process '/usr/bin/tar' failed with exit code 2
Saved a new cache.
Purging cache(s) created before 2024-10-24T14:38:05.105Z, scoped to "refs/heads/main", and with one of the key prefixes:
          [
"cache-linux-amd64-"
]
Found no cache(s).
Finished purging cache(s).
```
